### PR TITLE
chore: release as 1.0.0-rc1

### PR DESCRIPTION
**Pull request by parthea**
Release-As: 1.0.0-rc1

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]

**Comment by busunkim96** [comment]
@dandhlee Was there a specific schema we should use for release candidates to avoid breaking the docs pipeline?

**Comment by parthea** [comment]
On hold, pending response from @dandhlee

**Comment by dandhlee** [comment]
Sorry for the delay! I've made changes that should make this schema work, thanks for checking in. Just to be safe I've ran it in my system and it should work fine :D

**Comment by parthea** [comment]
Thanks for checking, @dandhlee!

**Pull request merged**
