### PR TITLE
feat: add v3

### LINKED ISSUE #2: Resource Manager: update API from `v1beta1` to `v3`
Python: 3.5.3
Operating System: Debian GNU
Pip Freeze:

google-api-core==1.3.0
google-api-python-client==1.7.4
google-auth==1.5.1
google-auth-httplib2==0.0.3
google-cloud-container==0.1.1
google-cloud-core==0.28.1
google-cloud-resource-manager==0.28.1
google-cloud-storage==1.11.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3

Stacktrace: 

Traceback (most recent call last):
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-gke-0KxaOTFM/bin/django_gke", line 11, in <module>
    load_entry_point('django-gke', 'console_scripts', 'django_gke')()
  File "/usr/local/google/home/epad/Projects/django-gke2/django-gke/django_gke/django_gke.py", line 253, in main
    args.func(args.debug)
  File "/usr/local/google/home/epad/Projects/django-gke2/django-gke/django_gke/django_gke.py", line 173, in new
    project_id = goog_client.create_project_workflow()
  File "/usr/local/google/home/epad/Projects/django-gke2/django-gke/django_gke/cli/google_client.py", line 111, in create_project_workflow
    project_id, project_name)
  File "/usr/local/google/home/epad/Projects/django-gke2/django-gke/django_gke/cloudlib/project.py", line 40, in create_and_set_existing_project
    self._create_project(project)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-gke-0KxaOTFM/lib/python3.5/site-packages/backoff/_sync.py", line 99, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/google/home/epad/Projects/django-gke2/django-gke/django_gke/cloudlib/project.py", line 55, in _create_project
    project.create()
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-gke-0KxaOTFM/lib/python3.5/site-packages/google/cloud/resource_manager/project.py", line 138, in create
    data=data)
  File "/usr/local/google/home/epad/.local/share/virtualenvs/django-gke-0KxaOTFM/lib/python3.5/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://cloudresourcemanager.googleapis.com/v1beta1/projects: The caller does not have permission

Steps to reproduce: Using Gcloud auth login with a non corp account and the attempting to project.create() will throw this error.

We are able to get this to work with corp accounts but will be doing external users soon and found that this fails. 

I believe changing the version [here](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/resource_manager/google/cloud/resource_manager/_http.py#L36) to v1 would fix this.

### PR DESCRIPTION
**Pull request by parthea**
Fixes #2  🦕

This PR adds the auto generated `v3` client for Resource Manager and changes the release status from `alpha` to `beta`. This is a significant change from the previous version `v1beta1`, as this is the first version of an auto generated client.  

chore(release_status): upgrade release status from alpha to beta
fix: remove v1beta1
chore(deps): require python 3.6+

### CODE REVIEW

**Review by busunkim96 — APPROVED** [review]
Hooray! Glad to see this get added.

Was the decision to delete all the existing code and take the breaking change?

**Comment by parthea** [comment]
@busunkim96 Yes, we decided to take this breaking change since this repository is at release level 'alpha'.  Users can pin `google-cloud-resource-manager<1.0.0` to avoid taking the breaking change. In addition, we want to roll this out using a pre-release so that only users that install using `pip install --pre` will receive it initially.   I'm going to hold off on merging this until I'm ready for the pre-release.

cc @danoscarmike

**Comment by parthea** [comment]
In preparation for the pre-release, I've successfully published a pre-release to testpypi [here](https://test.pypi.org/project/google-cloud-resource-manager/#history) for demonstration purposes. It looks like we need to add the suffix `rc<version>` to the version in order for it to be a pre-release, eg. 1.0.0rc1. We would need to have separate versioning strategies in `release-please` for stable and release candidate versions. For example, release candidates would increment like this 1.0.0rc1 , 1.0.0rc2… etc instead of 1.0.0 , 1.0.1 etc. I'm going to put this PR on hold while I figure out how to handle release candidates with release-please. There is a an open PR in `release-please` which may help : https://github.com/googleapis/release-please/pull/903 .

**Comment by parthea** [comment]
In order for release-please to handle pre-releases we need to include a `-` in the version number. See [here](https://github.com/googleapis/release-please/blob/39442a7e80397d1fd9b5b3e1ed956dfbd108c00a/src/release-pr.ts#L562). I'm going to merge this PR and then open a new PR to set the version to `1.0.0-rc1`

**Pull request merged**
